CREATE DATABASE IF NOT EXISTS ST_BACKEND DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

USE ST_BACKEND;

/*
创建用户表
*/
CREATE TABLE IF NOT EXISTS ST_USER(
	ID BIGINT AUTO_INCREMENTT,
	USER_ID VARCHAR(32) NOT NULL COMMENT '唯一标识',
	USERNAME VARCHAR(25) UNIQUE NOT NULL COMMENT '用户名',
	PASSWORD VARCHAR(25) NOT NULL COMMENT '加密后的密码',
	SALT VARCHAR(32) NOT NULL COMMENT '加密使用的salt',
	STATUS ENUM("I","A","L","D") DEFAULT 'I' NOT NULL COMMENT '用户账号状态，I: InActive; A: Active; L: Locked; D: Deleted',
	CREATE_TIME DATETIME COMMENT '创建日期',
	CREATE_BY VARCHAR(32) COMMENT '创建人',
	UPDATE_TIME DATETIME COMMENT '更新日期',
	UPDATE_BY VARCHAR(32) COMMENT '更新人',
	CONSTRAINT PK_ST_USER PRIMARY KEY(ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


/*
创建角色表
*/
CREATE TABLE IF NOT EXISTS ST_ROLE(
	ID BIGINT AUTO_INCREMENTT,
	ROLE_ID VARCHAR(32) NOT NULL COMMENT '唯一标识',
	ROLE_NAME VARCHAR(25) UNIQUE NOT NULL COMMENT '角色名称',
	ROLE_DESC VARCHAR(100) COMMENT '角色描述',、
	STATUS ENUM("I","A","D") DEFAULT 'I' NOT NULL COMMENT '角色状态，I: InActive; A: Active; D: Deleted',
	CREATE_TIME DATETIME COMMENT '创建日期',
	CREATE_BY VARCHAR(32) COMMENT '创建人',
	UPDATE_TIME DATETIME COMMENT '更新日期',
	UPDATE_BY VARCHAR(32) COMMENT '更新人',
	CONSTRAINT PK_ST_ROLE PRIMARY KEY(ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/*
创建资源表
*/
CREATE TABLE IF NOT EXISTS ST_RESOURCE(
	ID BIGINT AUTO_INCREMENTT,
	RESOURCE_ID VARCHAR(32) NOT NULL COMMENT '唯一标识',
	RESOURCE_NAME VARCHAR(25) UNIQUE NOT NULL COMMENT '资源名称',
	RESOURCE_DESC VARCHAR(100) COMMENT '资源描述',
	RESOURCE_TYPE ENUM("MENU","METHOD","OTHERS") COMMENT '资源类型，MENU:菜单，METHOD：方法调用, OTHERS：页面的按钮等 ',
	STATUS ENUM("I","A","D") DEFAULT 'A' NOT NULL COMMENT '资源状态，I: InActive; A: Active; D: Deleted',
	PARENT_ID VARCHAR(32) COMMENT '父资源ID',
	CREATE_TIME DATETIME COMMENT '创建日期',
	CREATE_BY VARCHAR(32) COMMENT '创建人',
	UPDATE_TIME DATETIME COMMENT '更新日期',
	UPDATE_BY VARCHAR(32) COMMENT '更新人',
	CONSTRAINT PK_ST_RESOURCE PRIMARY KEY(ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/*
创建用户-角色关系表
*/
CREATE TABLE IF NOT EXISTS ST_USER_ROLE_RELATION(
	USER_ID VARCHAR(32) NOT NULL COMMENT '用户唯一标识',
	ROLE_ID VARCHAR(32) NOT NULL COMMENT '角色唯一标识',
	CREATE_TIME DATETIME COMMENT '创建日期',
	CREATE_BY VARCHAR(32) COMMENT '创建人',
	UPDATE_TIME DATETIME COMMENT '更新日期',
	UPDATE_BY VARCHAR(32) COMMENT '更新人',
	CONSTRAINT PK_ST_USER_ROLE_RELATION PRIMARY KEY(USER_ID, ROLE_ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


/*
创建角色-资源关系表
*/
CREATE TABLE IF NOT EXISTS ST_ROLE_RESOURCE_RELATION(
	ROLE_ID VARCHAR(32) NOT NULL COMMENT '角色唯一标识',
	RESOURCE_ID VARCHAR(32) NOT NULL COMMENT '资源唯一标识',
	CREATE_TIME DATETIME COMMENT '创建日期',
	CREATE_BY VARCHAR(32) COMMENT '创建人',
	UPDATE_TIME DATETIME COMMENT '更新日期',
	UPDATE_BY VARCHAR(32) COMMENT '更新人',
	CONSTRAINT PK_ST_ROLE_RESOURCE_RELATION PRIMARY KEY(RESOURCE_ID, ROLE_ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/*
TODO : 插入测试数据【待系统功能完成后添加】
*/


